### ISSUE TITLE
Remove false negative for Organization Private repositories

### ISSUE THREAD

**Issue by jatin-mehrotra-colorkrew** [UmbrellaDocs/action-linkspector#15]
**Is your feature request related to a problem? Please describe.**

I have an organization which has private repositories. We use wiki for maintaining our documentation and we link many repositories in our documentation. While running this GHA it also flags working links ( private repository of my organizations)

**Describe the solution you'd like**

My organization private repository should not be flagged

**Describe alternatives you've considered**

NA

**Additional context**

Code I am using 

```
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run linkspector
        uses: umbrelladocs/action-linkspector@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          fail_on_error: true
          config_file: '.github/ci-check-configs/.linkspector.yml'
```
