### ISSUE TITLE
Migeation guide from https://github.com/gaurav-nelson/github-action-markdown-link-check

### ISSUE THREAD

**Issue by matifali** [UmbrellaDocs/action-linkspector#17]
Provide a migration guide from using the https://github.com/gaurav-nelson/github-action-markdown-link-check to the linkspector.

**Comment by matifali** [comment]
Are there any plans to support this?

**Comment by gaurav-nelson** [comment]
# Migration Guide: github-action-markdown-link-check to action-linkspector

This guide helps you migrate from [`gaurav-nelson/github-action-markdown-link-check`](https://github.com/gaurav-nelson/github-action-markdown-link-check) to [`UmbrellaDocs/action-linkspector`](https://github.com/UmbrellaDocs/action-linkspector).

> **Note:** `github-action-markdown-link-check` was deprecated in April 2025. `action-linkspector` is one of the recommended replacements.

## What's different?

| Feature | markdown-link-check | action-linkspector |
|---|---:|---:|
| File formats | Markdown only | Markdown + AsciiDoc |
| Configuration file | `mlc_config.json` (JSON) | `.linkspector.yml` (YAML) |
| PR reporting | Annotations only | Reviewdog integration (PR comments, checks) |
| Link checking engine | `markdown-link-check` (Node) | Linkspector (Node + Puppeteer headless Chrome fallback) |
| False positives | Common on JS-rendered pages | Fewer (headless Chrome fallback) |

## Step 1: Update your workflow file

**Before:**

```yaml
name: Check Markdown links
on: push

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          config-file: 'mlc_config.json'
          folder-path: 'docs'
          check-modified-files-only: 'yes'
          base-branch: 'main'
```

**After:**

```yaml
name: Linkspector
on: pull_request

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: umbrelladocs/action-linkspector@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          fail_level: any
          config_file: '.linkspector.yml'
```

### Input mapping

| markdown-link-check input | action-linkspector equivalent |
|---|---|
| `config-file` | `config_file` |
| `use-quiet-mode` | `fail_level: any` (errors only) |
| `check-modified-files-only` | `filter_mode: added` (default) or set `modifiedFilesOnly: true` in config |
| `folder-path` | Set `dirs` in `.linkspector.yml` |
| `file-path` | Set `files` in `.linkspector.yml` |
| `file-extension` | Set `fileExtensions` in `.linkspector.yml` |
| `base-branch` | Not needed (reviewdog handles this automatically) |
| `use-verbose-mode` | `show_stats: true` |
| `max-depth` | Not available (use `excludedDirs` instead) |

### Reporter options

The `reporter` input controls how results appear:

- `github-pr-review` -- Posts inline review comments on the PR (recommended)
- `github-pr-check` -- Adds a check run with annotations (default)
- `github-check` -- Creates a separate check run

### Filter modes

The `filter_mode` input controls which errors are reported:

- `added` (default) -- Only errors on newly added lines
- `diff_context` -- Errors in changed lines and surrounding context
- `file` -- All errors in modified files
- `nofilter` -- All errors across the repository

## Step 2: Convert your configuration file

Migrate from `mlc_config.json` to `.linkspector.yml`.

**Before (`mlc_config.json`):**

```json
{
  "ignorePatterns": [
    { "pattern": "^https://example.com" }
  ],
  "replacementPatterns": [
    { "pattern": "^https://docs.example.com", "replacement": "https://staging.example.com" }
  ],
  "aliveStatusCodes": [200, 206, 429],
  "retryOn429": true,
  "retryCount": 3,
  "fallbackRetryDelay": "30s",
  "httpHeaders": [
    {
      "urls": ["https://github.com"],
      "headers": { "Accept": "text/html" }
    }
  ]
}
```

**After (`.linkspector.yml`):**

```yaml
dirs:
  - .

ignorePatterns:
  - pattern: "^https://example\\.com"

replacementPatterns:
  - pattern: "^https://docs\\.example\\.com"
    replacement: "https://staging.example.com"

aliveStatusCodes:
  - 200
  - 206
  - 429

retryCount: 3

httpHeaders:
  - url:
      - https://github.com
    headers:
      Accept: text/html

useGitIgnore: true
```

### Configuration mapping

| mlc_config.json | .linkspector.yml | Notes |
|---|---|---|
| `ignorePatterns[].pattern` | `ignorePatterns[].pattern` | Same regex syntax |
| `replacementPatterns` | `replacementPatterns` | Same structure |
| `aliveStatusCodes` | `aliveStatusCodes` | Same |
| `httpHeaders[].urls` | `httpHeaders[].url` | Key renamed from `urls` to `url` |
| `httpHeaders[].headers` | `httpHeaders[].headers` | Same; supports `${ENV_VAR}` syntax |
| `retryOn429` | Not needed | Handled automatically |
| `retryCount` | `retryCount` | Same (default: 3) |
| `fallbackRetryDelay` | Not available | Uses exponential backoff automatically |
| -- | `timeout` | New: request timeout in ms (default: 30000) |
| -- | `baseUrl` | New: base URL for relative links |
| -- | `excludedFiles` | New: files to skip |
| -- | `excludedDirs` | New: directories to skip |
| -- | `followRedirects` | New: report redirects as errors |
| -- | `userAgent` | New: custom User-Agent string |
| -- | `ignoreSslErrors` | New: skip SSL validation |

## Step 3: Remove inline suppression comments

Linkspector does **not** support inline HTML comments for suppressing link checks. Remove these and use `ignorePatterns` in your config instead:

```diff
- <!-- markdown-link-check-disable-next-line -->
- [Example](https://example.com/maybe-broken)
```

Replace with a pattern in `.linkspector.yml`:

```yaml
ignorePatterns:
  - pattern: "^https://example\\.com/maybe-broken$"
```

## Step 4: Verify

1. Commit your new `.linkspector.yml` and updated workflow file.
2. Open a pull request to trigger the action.
3. Check the PR for reviewdog comments or check run annotations.
4. Once satisfied, delete the old `mlc_config.json` file.
