### ISSUE TITLE
linkspector + reviewdog not catching broken links

### ISSUE THREAD

**Issue by brunopgalvao** [UmbrellaDocs/action-linkspector#20]
Hello! 

I have broken links in my [README.md](https://github.com/brunopgalvao/base-parachain/blob/cf079afff7af276625518d27f0da472af01f892e/README.md?plain=1#L21-L23) and the linkspector action does not seem to be catching it.

Here is the workflow:
```yml
name: Linkspector
on: [push]
jobs:
  check-links:
    name: runner / linkspector
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: List all files (Debugging)
        run: |
          echo "Listing all files to be scanned:"
          ls -R .
      - name: Run linkspector with reviewdog flags
        uses: umbrelladocs/action-linkspector@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check  # You can still specify the reporter here
          fail_on_error: true
          config_file: ".github/workflows/.linkspector.yml"
```
- https://github.com/brunopgalvao/base-parachain/blob/main/.github/workflows/linkchecker.yml

@gaurav-nelson any help here would be appreciated 🙏🏻
