### ISSUE TITLE
Running with `modifiedFilesOnly` fails with reviewdog parse error

### ISSUE THREAD

**Issue by Realiserad** [UmbrellaDocs/action-linkspector#3]
**Describe the bug**

Running Linkspector GitHub Action with a custom config results containing `modifiedFilesOnly: true` results in a reviewdog parse error.

**To Reproduce**

Copy-paste the following into `.github/workflows/linkspector.yaml` and create a PR:

```yaml
name: Linkspector
on:
  pull_request:
jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: 1arp/create-a-file-action@0.4.5
      with:
        file: .linkspector.yml
        content: |
          dirs: ['.']
          useGitIgnore: true
          modifiedFilesOnly: true
    - name: Run Linkspector
      uses: UmbrellaDocs/action-linkspector@v1.0.0
      with:
        github_token: ${{ secrets.github_token }}
        reporter: github-pr-review
```

The error from GitHub Actions is:

```
reviewdog: parse error: failed to unmarshal rdjson (DiagnosticResult): proto: syntax error (line 1:1): invalid value Skipped
```

**Expected behavior**

The workflow should pass without errors.
