### ISSUE TITLE
Action fails on `arm64` runners

### ISSUE THREAD

**Issue by WyriHaximus** [UmbrellaDocs/action-linkspector#44]
**Describe the bug**
Action fails to run on `arm64` because it tries to run `amd64` code:

![Image](https://github.com/user-attachments/assets/a09922c5-d0e0-4153-a677-7747b439dfb2)

**To Reproduce**

Run the following workflow on a `arm64` machine:
```yaml
name: Check Markdown links

on:
  workflow_call:
    inputs:
      runsOn:
        description: Define on which runner this workflow should run
        default: "ubuntu-latest"
        required: false
        type: string
      workingDirectory:
        description: The directory to run this workflow in
        default: ""
        required: false
        type: string

#defaults:
#  run:
#    working-directory: ${{ inputs.workingDirectory }}

jobs:
  markdown-link-check:
    name: Check Markdown links
    runs-on: ${{ inputs.runsOn }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            !${{ inputs.workingDirectory }}/*
            ${{ inputs.workingDirectory }}/**/*.md
      - name: Check Markdown links
        uses: umbrelladocs/action-linkspector@v1
        with:
          reporter: github-pr-review
          fail_on_error: true
#          config_file: etc/ci/markdown-link-checker.json
```

**Expected behavior**
Action successfully runs on `arm64`, this is from another project about 6 to 7 hours ago:

![Image](https://github.com/user-attachments/assets/4c257028-f539-448d-bdda-f0247ce9f441)

**Additional context**
Running this actions on GitHub shared runners for my public repos, and on Raspberry Pi's on my home cluster for private repositories
